manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # support nice_oled and nice_epaper
    - name: xenosf                         #new entry
      url-base: https://github.com/xenosf  #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      # revision: 241ff39556b3685c9344c4c22fd9a655af8eb3ba
      revision: main
      import: app/west.yml
    # This is not working, remove in next build
    - name: nice-view-gem
      remote: xenosf                       #new entry
      revision: main                      #new entry
  self:
    path: config