manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # support nice_oled and nice_epaper
    - name: carlosarceleon                         #new entry
      url-base: https://github.com/carlosarceleon  #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # support nice_oled and nice_epaper
    - name: nice-view-gem
      remote: carlosarceleon                       #new entry
      revision: try_fix                      #new entry
  self:
    path: config